const cat = {
    tvAndAudio: "tvAndAudio",
    tvBox: "tvBox",
    powerTools: "powerTools",
    headphones: "headphones",
    cellPhones: "cellPhones",
    smartWatches: "smartWatches",
    gameAndVideo: "gameAndVideo",
    robotClean: "robotClean",
    sportWatches: "sportWatches",
    tablets: "tablets",
    computersAndLaptop: "computersAndLaptop",
    camerasAndPhotos: "camerasAndPhotos",
  };
  export const categories = [
    {
      _id: 1001,
      name: "TV & Audio",
      image: "https://www.kigalidiscount.com/cdn/shop/files/wbbbb_60245703-b801-4c6b-b2c3-067fa65dc4d3_800x.png?v=1699368024",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "tvAndAudio",
    },
    {
      _id: 1002,
      name: "TV Box",
      image: "https://m.media-amazon.com/images/I/81pieXC63IL._AC_SL1500_.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "tvBox",
    },
    {
      _id: 1003,
      name: "Power Tools",
      image: "https://dam.thdstatic.com/content/production/UOkOZqrY_9FOZXCijltynQ/Ox4tEx11QjCqLYCBC1Kr9w/Original%20file/eb9fe5ce-a6ae-4f07-b949-2e60b2911a19_300DPI_1000px-DCD794D1_3.jpeg?im=Resize=(703,703)",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "powerTools",
    },
    {
      _id: 1004,
      name: "Headphones",
      image: "https://m.media-amazon.com/images/I/51aHcGncblL._AC_SL1000_.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "headphones",
    },
    {
      _id: 1005,
      name: "Cell Phones",
      image: "https://m.media-amazon.com/images/I/61cTi9MBqOL._AC_SL1500_.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "cellPhones",
    },
    {
      _id: 1006,
      name: "Smart Watches",
      image: "https://m.media-amazon.com/images/I/61yEHZXdi6L._AC_UF1000,1000_QL80_.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "smartWatches",
    },
    {
      _id: 1007,
      name: "Game & Video",
      image: "https://mcprod.hnak.com/media/catalog/product/4/3/43e273011a41e402386a5a3e6073ece636ab8b41ca8e3a532157ed973f89ddd6.jpeg?quality=60&fit=bounds&height=&width=",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "gameAndVideo",
    },
    {
      _id: 1008,
      name: "Robot Clean",
      image: "https://supplymaster.store/cdn/shop/files/karcher-karcher-robotic-vacuum-cleaner-with-wiping-function-rcv-3-steam-vacuum-cleaner-32517717950598.jpg?v=1717834517&width=1214",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "robotClean",
    },
    {
      _id: 1009,
      name: "Sport Watches",
      image: "https://m.media-amazon.com/images/I/91vtZGxK0JL._AC_SL1500_.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "sportWatches",
    },
    {
      _id: 1010,
      name: "Tablets",
      image: "https://ishop.com.gh/images/ipadhome/air10/ipad-air-10-all.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "tablets",
    },
    {
      _id: 1011,
      name: "Computers & Laptop",
      image: "https://cdn.gamenotebaku.az/productimg/108/419/gamenote_img_62_1710434995.png.webp",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "computersAndLaptop",
    },
    {
      _id: 1012,
      name: "Cameras & Photos",
      image: "https://m.media-amazon.com/images/I/718DXOeP5vL.jpg",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
      _base: "camerasAndPhotos",
    },
  ];
  
  export const highlightsProducts = [
    {
      _id: 3001,
      name: "New Deals at Best Prices",
      title: "From $4000.00",
      buttonTitle: "Browse Deals",
      image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienwar-x16-mlk/pdp/laptop-alienware-x16r2-mlk-pdp-banner-form.psd?fmt=jpg&wid=3000&hei=1000",
      _base: "/product",
      color: "#000000",
    },
    {
      _id: 3002,
      name: "Colorful Redmi  Note 6 Pro",
      title: "From $40.00",
      buttonTitle: "Shop Cellphone",
      image: "https://www.apple.com/newsroom/videos/videos-2024/autoplay/2024/09/apple-iphone-16-pro-light-and-durable-upgraded-design/posters/Apple-iPhone-16-Pro-light-and-durable-upgraded-design-240909.jpg.large_2x.jpg",
      _base: "/category/cellPhones",
      color: "#ffffff",
    },
    {
      _id: 3003,
      name: "1000 mAh Power Bank",
      title: "From $40.00",
      buttonTitle: "Shop Now",
      image: "https://powerbankexpert.home.blog/wp-content/uploads/2019/06/banner_312.jpg",
      _base: "/product",
      color: "#ffffff",
    },
  ];
  
  export const blogsData = [
    {
      _id: 4001,
      image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
      title: "iPhone 15 rear camera design will be available",
      _base: "Technology",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
    {
      _id: 4002,
      image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
      title: "Setup your surround sound speaker",
      _base: "Samrt thing",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
    {
      _id: 4003,
      image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
      title: "Hook up a receiver for your home theater",
      _base: "Life style",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
    },
  ];
  
  export const products = [
    {
      _id: 2001,
      name: "JBL CHARGE 5 - Portable Waterproof (IP67) Bluetooth Speaker with Powerbank USB Charge out, 20 hours playtime, JBL Partyboost (Black)",
      images: [
        "https://dynamic.zacdn.com/9L3KFf-qnswAjUhcjgDHi095r1k=/filters:quality(70):format(webp)/https://static-id.zacdn.com/p/jbl-6648-1075983-1.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL-cus_vv2BiuMQ6iziQbUBhd1kDb_ChFd1Q&s",
        "https://static.wixstatic.com/media/7fbb56_2946ab2baa94424f82122eb74e41af67~mv2.jpg/v1/fill/w_980,h_980,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/7fbb56_2946ab2baa94424f82122eb74e41af67~mv2.jpg",
        "https://www.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw915dda4b/pdp/JBL_Charge_5_Lifestyle1_904x560px.png?sw=904&sh=560",
        "https://mercurycomputerslimited.com/wp-content/uploads/2023/12/JBL-Xtreme-3-Portable-Bluetooth-Speaker-gallery-4.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 580,
      quantity: 1,
      rating: 4.5,
      reviews: 50,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "JBL",
      isStock: true,
      overView: "Blutooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2002,
      name: "LEVOIT Air Purifiers for Home Large Room Up to 1800 Ft² in 1 Hr with Washable Pre-Filter, Air Quality Monitor, Smart WiFi, HEPA Sleep Mode for Allergies, Pet Hair in Bedroom, Vital 200S-P, White",
      images: [
        "https://cdn.mafrservices.com/pim-content/UAE/media/product/3233001420304/1737050206/3233001420304_main.jpeg?im=Resize=480",
        "https://m.media-amazon.com/images/I/71egJf713hL._AC_UF894,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/81cRt146vWL.jpg",
        "https://m.media-amazon.com/images/I/81W3kR2p5pL._AC_UF894,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/91il3FSGvBL._AC_UF894,1000_QL80_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 250,
      discountedPrice: 180,
      quantity: 1,
      rating: 4.8,
      reviews: 80,
      category: "Air Purifiers",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Levoit",
      isStock: true,
      overView: "Air purifier",
      isNew: false,
      _base: cat?.airPurifiers,
    },
    {
      _id: 2003,
      name: "Fitness M3 Color Screen Smart Sport Bracelet Activity Running Tracker Heart Rate For Children Men Women Watch For IOS Android",
      images: [
        "https://ae01.alicdn.com/kf/H880ec942c67046469a5d8da3ee922761e.jpg",
        "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/67/6713542/2.jpg?0473",
        "https://m.media-amazon.com/images/I/7111q1LH5iL._AC_UF350,350_QL80_.jpg",
        "https://img.joomcdn.net/6ce11752759bf856458be99c5a22282cfb07bc9a_original.jpeg",
        "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/67/6713542/1.jpg?0473",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 650,
      discountedPrice: 570,
      quantity: 1,
      rating: 4.2,
      reviews: 30,
      category: "Sport Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "MI Exclusive",
      isStock: true,
      overView: "Smart health watch",
      isNew: true,
      _base: cat?.sportWatches,
    },
    {
      _id: 2004,
      name: "SJ8 Air 1290P 4K 60fps Action Camera WIFI Remote Control Waterproof Sports DV FPV Camera",
      images: [
        "https://www.sjcam.co.uk/cdn/shop/products/sjcam-sj8-air-black_1024x1024.jpg?v=1695161695",
        "https://images-na.ssl-images-amazon.com/images/I/71-qxpnpldL._AC_UL495_SR435,495_.jpg",
        "https://m.media-amazon.com/images/I/81OBSsvmLzL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/7108x0gEIqL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71HH+BZoKtL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 400,
      discountedPrice: 350,
      quantity: 1,
      rating: 4.2,
      reviews: 120,
      category: "Camera & Photos",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: false,
      overView: "Cameras & Photos",
      isNew: false,
      _base: cat?.camerasAndPhotos,
    },
    {
      _id: 2005,
      name: "Redmi Xiaoai Speaker Play 2.4GHz 1.75 Inch Voice Remote Control Music Player Bluetooth 4.2 Mi Speaker For Android Iphone",
      images: [
        "https://justautoparts.com.au/wp-content/uploads/2024/02/product_supergear_17_4-655x655.jpg",
        "https://ae01.alicdn.com/kf/Sd3b97c3f9f324d7e949284f2a2116999A.jpg_640x640q90.jpg",
        "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/47/2975752/1.jpg?5225",
        "https://ae01.alicdn.com/kf/S8c0a108fa5874d4c84e7ef9731091e3cK.jpg_640x640q90.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtTOsADooMGvjyrlmtFlyqRSa-2nWQ3TGHd5R5_ViH170bI3rsI19WJFAx1lVrHfkP0rs&usqp=CAU",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 90,
      discountedPrice: 80,
      quantity: 1,
      rating: 4.2,
      reviews: 20,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Blutooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2006,
      name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
      images: [
        "https://m.media-amazon.com/images/I/512ZP+ATv3L._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/61NpsoqDVfL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/41LnT-rtfyL._AC_.jpg",
        "https://m.media-amazon.com/images/I/413t-hvO+uL._AC_.jpg",
        "https://m.media-amazon.com/images/I/41LnT-rtfyL._AC_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 300,
      discountedPrice: 280,
      quantity: 1,
      rating: 4.8,
      reviews: 110,
      category: "Smart Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Smart health watch",
      isNew: false,
      _base: cat.smartWatches,
    },
    {
      _id: 2007,
      name: "Beats Solo 4 - Wireless Bluetooth On-Ear Headphones, Apple & Android Compatible, Up to 50 Hours of Battery Life - Matte Black (Renewed)",
      images: [
        "https://images-cdn.ubuy.co.in/6441567475d14259fb674414-new-in-sealed-beats-by-dr-dre-studio.jpg",
        "https://www-konga-com-res.cloudinary.com/f_auto,fl_lossy,dpr_3.0,q_auto/media/catalog/product/J/T/122138_1721390743.jpg",
        "https://media.istockphoto.com/id/1471767738/photo/a-cheerful-woman-laughing-dancing-and-enjoying-music-while-standing-isolated-on-red-background.jpg?s=612x612&w=0&k=20&c=0ydiqllmvz0XxhjoPHEwZoy8z83g2rk7uIpVbs54pgs=",
        "https://i.ibb.co/tcdSfrr/blueGun.jpg",
        "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/6a35b4147099205.62bc3f0807d71.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 550,
      quantity: 1,
      rating: 4,
      reviews: 60,
      category: "Headphones & Speakers",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Beats",
      isStock: true,
      overView: "Microphones",
      isNew: true,
      _base: cat.headphones,
    },
    {
      _id: 2008,
      name: "New Product Form Lapbook Light Handlift Business Office Game Ben EDP 13.5 In – Black China",
      images: [
        "https://m.media-amazon.com/images/I/71Owrga0FjL._AC_UF350,350_QL50_.jpg",
        "https://m.media-amazon.com/images/I/71cit5wE+jL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61Chs0kX8nL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71zZx+8SINL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81hcAfx+X3L._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 1100,
      discountedPrice: 1080,
      quantity: 1,
      rating: 4.7,
      reviews: 190,
      category: "Computers & Laptops",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Msi",
      isStock: true,
      overView: "Computer Components",
      isNew: false,
      _base: cat?.computersAndLaptop,
    },
    {
      _id: 2009,
      name: "VIOMI V2 Pro LDS Sensor 2 In 1 Sweeping Mopping Robot Wet And Dry Vacuum Cleaner 2100Pa Strong Suction Self-Charging",
      images: [
        "https://m.media-amazon.com/images/I/518fzwDKbvL._AC_UF894,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51pSX3eMiYL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/41cuOA3L82L._AC_SL1380_.jpg",
        "https://www.gearbest.ma/wp-content/uploads/2024/01/Original-VIOMI-V2-PRO-2-In-1-LDS-SLAM-Robot-Vacuum-Cleaner-for-Home-Wet-Dry.webp",
        "https://m.media-amazon.com/images/I/31UGRUqhr9L._AC_SL1000_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 450,
      discountedPrice: 380,
      quantity: 1,
      rating: 4.2,
      reviews: 70,
      category: "Robot Clean",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "VIOMI",
      isStock: true,
      overView: "Robot Clean",
      isNew: true,
      _base: cat?.robotClean,
    },
    {
      _id: 2010,
      name: "Apple iPhone 16 Pro Max 1 TB: 5G mobile phone with camera, 4K 120 Dolby Vision and a big bow in battery life. Function with AirPods, Titan Still",
      images: [
        "https://m.media-amazon.com/images/I/61s1P+29yoL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61yP7WrviJL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/817NN0ZWt-L._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/717Uf63E91L._AC_SL1500_.jpg",
        "https://i.ytimg.com/vi/_SO_3ZJgahE/maxresdefault.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 1299,
      discountedPrice: 1199,
      quantity: 1,
      rating: 4.1,
      reviews: 160,
      category: "Cell Phones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Cual Sim Phones",
      isNew: true,
      _base: cat?.cellPhones,
    },
    {
      _id: 2011,
      name: "Jennov 2K Security Camera Outdoor, PTZ Wifi Home CCTV Camera 360° View with Auto Tracking, 24/7 Recording, Color Night Vision, Motion Detection, 2-way audio.",
      images: [
        "https://m.media-amazon.com/images/I/71tUUA5uBXL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71AycG8bZ0L._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71kR5bq+cQL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61OAdtsotnL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71xill8fr3L._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 350,
      discountedPrice: 280,
      quantity: 1,
      rating: 3.8,
      reviews: 250,
      category: "Cameras & Photos",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Security & Protection",
      isNew: true,
      _base: cat?.camerasAndPhotos,
    },
    {
      _id: 2012,
      name: "Electric Hot Melt Glue Gun Cordless Repair DIY Tool Heating Mini Glue Gun With Glue Sticks",
      images: [
        "https://www.bostik.com/files/live/sites/shared_bostik/files/Images/Australia/Products/C%26C/bostik-tg4x-hot-glue-gun-400x300.jpg",
        "https://m.media-amazon.com/images/I/91EdkMTyNlL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81W6nbHy3GL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/51btdHmrd8L._AC_SL1161_.jpg",
        "https://m.media-amazon.com/images/I/51Gn4h01pVL._AC_SL1118_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 150,
      discountedPrice: 80,
      quantity: 1,
      rating: 4.7,
      reviews: 90,
      category: "Power Tools",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Power Tools",
      isNew: true,
      _base: cat?.powerTools,
    },
    {
      _id: 2013,
      name: "MECOOL KH3 Android 10.0 Smart 4K 60fps TV Box – Black 2GB RAM + 16GB ROM",
      images: [
        "https://m.media-amazon.com/images/I/61MC3zk1AbL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/71ZE0LL1ftL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/61Gs-D7T1hL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/71NE+HOnE2L._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/61Gs-D7T1hL._AC_SL1000_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 56,
      discountedPrice: 50,
      quantity: 1,
      rating: 3.9,
      reviews: 100,
      category: "TV Box",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "TV Box",
      isNew: true,
      _base: cat?.tvBox,
    },
    {
      _id: 2014,
      name: "Xbox Wireless Controller - Pulse Red Series X",
      images: [
        "https://m.media-amazon.com/images/I/61yN9JFXG7S._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61JXRgMR0xS._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61a9U8ur3dS._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/51iDs9NM-yS._AC_SL1500_.jpg",
        "https://videogamesplus.ca/cdn/shop/files/Xbox_Controller_XS_PulseCipher_AOC_ANL_700x700.jpg?v=1737483508",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 80,
      discountedPrice: 75,
      quantity: 1,
      rating: 4.2,
      reviews: 110,
      category: "Game and Video",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Game & Video",
      isNew: true,
      _base: cat?.gameAndVideo,
    },
    {
      _id: 2015,
      name: "GSR 120-Li Hand Drill 12V Lithium Drill Household Power Tool Screwdriver With One Battery – GSR120-LI 1Battery",
      images: [
        "https://m.media-amazon.com/images/I/71iTf-EbQgL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/710nKU-5juL._AC_SL1500_.jpg",
        "https://i.ibb.co/wdV3b9q/vaccum.webp",
        "https://m.media-amazon.com/images/I/51uFKHKPyaL._AC_SL1001_.jpg",
        "https://m.media-amazon.com/images/I/61+zu7OeFcL._AC_SL1200_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 120,
      discountedPrice: 110,
      quantity: 1,
      rating: 4,
      reviews: 300,
      category: "Power Tools",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Power Tools",
      isNew: true,
      _base: cat?.powerTools,
    },
    {
      _id: 2016,
      name: "Xiaomi Mi Outdoor Speaker Bluetooth 5.0 IP55 Waterproof Dustproof Portable Wireless Speaker",
      images: [
        "https://m.media-amazon.com/images/I/61PyZW5-cAL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/519ai0e27fL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/51Y56FEbDlL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/61IuUXA4ETL._AC_SL1200_.jpg",
        "https://m.media-amazon.com/images/I/61wwcEdcN3L._AC_SL1200_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 250,
      discountedPrice: 240,
      quantity: 1,
      rating: 4.2,
      reviews: 110,
      category: "TV and Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Blutooth Speakers",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2017,
      name: "Global Version Mi TV Stick Android TV 9.0 Smart 2K HDR 1GB RAM 8GB ROM Bluetooth 4.2 Mini TV Dongle",
      images: [
        "https://m.media-amazon.com/images/I/51QlmXNlo6L._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/51fBnEU6orL._AC_.jpg",
        "https://m.media-amazon.com/images/I/41Ti0Md0RmL._AC_SL1024_.jpg",
        "https://m.media-amazon.com/images/I/512goI24b5L._AC_.jpg",
        "https://www.alezay.com/wp-content/uploads/2020/07/XIAOMI-MI-TV-STICK-PACKAGE.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 60,
      discountedPrice: 55,
      quantity: 1,
      rating: 4,
      reviews: 100,
      category: "TV Box",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "TV Box",
      isNew: true,
      _base: cat?.tvBox,
    },
    {
      _id: 2018,
      name: "Xiaomi Mijia LCD Writing Tablet With Pen 10 13.5inch Digital Drawing Message Graphics Electronic Handwriting Pad With Pen",
      images: [
        "https://m.media-amazon.com/images/I/51L1LPgrnfL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/411Z+Gt+7KL._AC_SL1300_.jpg",
        "https://m.media-amazon.com/images/I/61+OttumRML._AC_SL1312_.jpg",
        "https://m.media-amazon.com/images/I/51DnnghcknS._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/61rjRCoWAcS._AC_SL1000_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 350,
      discountedPrice: 330,
      quantity: 1,
      rating: 4.2,
      reviews: 70,
      category: "Tablets",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Tablets",
      isNew: true,
      _base: cat?.tablets,
    },
    {
      _id: 2019,
      name: "New Creative Cloth Art Home Outdoors Bluetooth Sound Box",
      images: [
        "https://m.media-amazon.com/images/I/71Q0n8LhWyL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/61tLBrZk-vL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/61ycfXSpSeL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/71afn7SaGSL._AC_SL1000_.jpg",
        "https://m.media-amazon.com/images/I/710MWcA9-QL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 120,
      discountedPrice: 100,
      quantity: 1,
      rating: 4.1,
      reviews: 20,
      category: "Bluetooth Speakers",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Bluetooth Speakers",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2020,
      name: "SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI Smartphone, Unlocked Android, AI Camera, Fast Processor, Long Battery Life, 2025, US 1 Yr Manufacturer.",
      images: [
        "https://m.media-amazon.com/images/I/61n0lmxP5-L._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71yEnCyYTbL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71OPsyfsDGL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71bWBcWQnDL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61CmIlFRMjL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 1599,
      discountedPrice: 1499,
      quantity: 1,
      rating: 3.7,
      reviews: 190,
      category: "Cell Phones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Samsung",
      isStock: true,
      overView: "Dual Sim Phones",
      isNew: true,
      _base: cat?.cellPhones,
    },
    {
      _id: 2021,
      name: "L21 Bluetooth Earphone Wireless Earbuds 5.0 TWS Headsets Dual Earbuds Bass Sound For Huawei Xiaomi IPhone Samsung Mobile Phones",
      images: [
        "https://m.media-amazon.com/images/I/71FlkpjxJRL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/61htfUqohbL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/712MxS7N9hL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/715cNJO1AFL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71K+frFyTVL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 35,
      discountedPrice: 32,
      quantity: 1,
      rating: 3.9,
      reviews: 10,
      category: "Headphones",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Fitness Headphones",
      isNew: true,
      _base: cat?.headphones,
    },
    {
      _id: 2022,
      name: "BLACK+DECKER Small Portable Washer, Washing Machine for Household Use, Portable Washer 1.7 Cu. Ft. with 6 Cycles, Transparent Lid & LED Display",
      images: [
        "https://m.media-amazon.com/images/I/71vqOmBCNGL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71IAARpsmEL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81aztLKaiVL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81IA5mOfGjL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/811E7B4JtTL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 950,
      discountedPrice: 920,
      quantity: 1,
      rating: 4.2,
      reviews: 100,
      category: "Robot Clean",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Robot Clean",
      isNew: true,
      _base: cat?.robotClean,
    },
    {
      _id: 2023,
      name: "Sony SRS-XP700 X-Series Wireless Portable-BLUETOOTH-Karaoke Party-Speaker IPX4 Splash-resistant with 25 Hour-Battery,Black",
      images: [
        "https://m.media-amazon.com/images/I/81CChBWuhRS._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81dxPwZ5GWL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71PbXSVomrL._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71r0pyX0UaS._AC_SL1500_.jpg",
        "https://m.media-amazon.com/images/I/711tNOMqomL._AC_SL1500_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 600,
      discountedPrice: 580,
      quantity: 1,
      rating: 4.7,
      reviews: 200,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Bluetooth Speaker",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2024,
      name: "1TB iPod Classic 7th Generation Space Gray (MP3 Player, upgraded, 1000.0 GB, FLAC support)",
      images: [
        "https://m.media-amazon.com/images/I/418ltkPz0pL._AC_.jpg",
        "https://m.media-amazon.com/images/I/61-Q4GxER+L._AC_SL1500_.jpg",
        "https://www.ishop.com.gh/images/ipod/classic/f2.jpg",
        "https://www.moneydigest.com/img/gallery/the-unexpected-value-of-your-old-ipod-today/intro-1713194094.jpg",
        "https://m.media-amazon.com/images/I/71PEP41wUDL._AC_UF1000,1000_QL80_.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 455,
      discountedPrice: 70,
      quantity: 1,
      rating: 4.2,
      reviews: 60,
      category: "TV & Audio",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "MP3 Player",
      isNew: true,
      _base: cat?.tvAndAudio,
    },
    {
      _id: 2025,
      name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
      images: [
        "https://i02.appmifile.com/mi-com-product/fly-birds/xiaomi-watch-s4/pc/83b9bf1fc1dd85c8511cdf069f16577a.jpg?f=webp",
        "https://cworld.id/wp-content/uploads/2025/03/252a3c8d-9f66-4f92-85c8-90100c9a631b.jpg",
        "https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc4/watch-s4-header.jpg",
        "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-watch-s4.jpg",
        "https://assets.hardwarezone.com/img/2024/10/Xiaomi_new_watches-2.jpg",
      ],
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
      regularPrice: 220,
      discountedPrice: 210,
      quantity: 1,
      rating: 4.5,
      reviews: 90,
      category: "Smart Watches",
      colors: ["red", "blue", "green", "yellow", "black", "white"],
      brand: "Lorem ipsum dolor sit",
      isStock: true,
      overView: "Smart Health Watch",
      isNew: true,
      _base: cat?.smartWatches,
    },
  ];